POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "is linking works ? ",
  "author": "king is bling ",
  "url": "www.g.com",
  "likes": 1000,
  "userId" : "65c36d23da771edfc8582861"
}